### ISSUE TITLE
issues launching docker cmd for "mistralai/Mistral-7B-Instruct-v0.2"

### ISSUE THREAD

**Issue by abhibst** [predibase/lorax#127]
### System Info

**using this official docker run cmd :** 

model=mistralai/Mistral-7B-Instruct-v0.2
volume=$PWD/data

docker run --gpus all --shm-size 1g -p 8080:80 -v $volume:/data \
    ghcr.io/predibase/lorax:latest --model-id $model

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

model=mistralai/Mistral-7B-Instruct-v0.2
volume=$PWD/data

docker run --gpus all --shm-size 1g -p 8080:80 -v $volume:/data \
    ghcr.io/predibase/lorax:latest --model-id $model
    
    
error:
2023-12-13T10:44:53.233748Z ERROR shard-manager: lorax_launcher: Shard complete standard error output:

Traceback (most recent call last):

  File "/opt/conda/bin/lorax-server", line 8, in <module>
    sys.exit(app())

  File "/opt/conda/lib/python3.9/site-packages/lorax_server/cli.py", line 81, in serve
    server.serve(

  File "/opt/conda/lib/python3.9/site-packages/lorax_server/server.py", line 262, in serve
    asyncio.run(

  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)

  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()

  File "/opt/conda/lib/python3.9/site-packages/lorax_server/server.py", line 214, in serve_inner
    model = get_model(

  File "/opt/conda/lib/python3.9/site-packages/lorax_server/models/__init__.py", line 274, in get_model
    return FlashMistral(

  File "/opt/conda/lib/python3.9/site-packages/lorax_server/models/flash_mistral.py", line 347, in __init__
    SLIDING_WINDOW_BLOCKS = math.ceil(config.sliding_window / BLOCK_SIZE)

TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'    

### Expected behavior

should run the sever with the model

**Comment by tgaddair** [comment]
Hey @abhibst, I can confirm this issue happens with the new v0.2 model, but not the v0.1. I'll try and put together a fix today.

**Comment by tgaddair** [comment]
@abhibst the issue should be resolved in the latest Docker images, let me know if this issue is resolved!
