### ISSUE TITLE
Add nf4 support for model quantization

### ISSUE THREAD

**Issue by geoffreyangus** [predibase/lorax#13]
### Feature request

There is existing code in LoRAX towards 8bit bitsandbytes quantization: https://github.com/predibase/lorax/blob/c747d27a8d1c9421fdcb4542191efe8553535763/server/text_generation_server/utils/layers.py#L86-L95

Supporting 4bit bitsandbytes quantization would enable us to serve models trained in 4bit.

The change should involve following the patterns implemented for 8bit quantization.

**Comment by runvnc** [comment]
Dumb question: does this already fully support 8 bit QLoRA then, or are there code changes or special configuration that's not obvious or spelled out in the README? I am using code from here: https://github.com/artidoro/qlora

Also how hard is to do the same or similar thing for 4bit? By the way this is an absolutely amazing project!

**Comment by runvnc** [comment]
It's probably easy enough to find, but this is the config for 4bit (I think) just for reference:

`
double_quant_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16
)
`

For now I am just trying to change my training script to use 8bit. If I get that working then maybe I can find time to come back and find where to put the 4bit stuff in this library.

**Comment by geoffreyangus** [comment]
I see! Good question. There is a `--quantize` flag that you can use when launching a deployment that we haven't tested super thoroughly yet. This flag accepts "bitsandbytes" and "gptq" as arguments: https://github.com/predibase/lorax/blob/2b2752de33ea7b27dc4a4c95e90f0db05785e0c5/launcher/src/main.rs#L28

My understanding is that using the "bitsandbytes" field here defaults to quantizing into 8 bit QLoRA: https://github.com/predibase/lorax/blob/2b2752de33ea7b27dc4a4c95e90f0db05785e0c5/server/lorax_server/utils/layers.py#L149-L157

I believe it shouldn't be too hard to add 4bit quantization– I think the only change would have to go to the above section in the code. Let me know if you'd be interested in making a contribution there!

**Comment by flozi00** [comment]
As far as I understand it would only takes a new 4 bit layer class and adding the 4 bit option to the python enum and the rust cli enum.

Should be around 20 lines of code
Can open draft pr tomorrow

**Comment by runvnc** [comment]
I appreciate all of the work on this project. I just got the container running last night. It's great to be able to swap out the LoRAs. Haven't tried any 8 bit quantization yet.

**Comment by runvnc** [comment]
Hello, I tried this with the new quantize option and it can't start the shard because `Params4bit is not defined`:

```
2023-11-27T22:18:41.941444Z ERROR shard-manager: lorax_launcher: Shard complete standard error output:

You are using a model of type llama to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
Traceback (most recent call last):

  File "/opt/conda/bin/lorax-server", line 8, in <module>
    sys.exit(app())

  File "/opt/conda/lib/python3.9/site-packages/lorax_server/cli.py", line 83, in serve
    server.serve(

  File "/opt/conda/lib/python3.9/site-packages/lorax_server/server.py", line 262, in serve
    asyncio.run(

  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)

  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()

  File "/opt/conda/lib/python3.9/site-packages/lorax_server/server.py", line 214, in serve_inner
    model = get_model(

  File "/opt/conda/lib/python3.9/site-packages/lorax_server/models/__init__.py", line 221, in get_model
    return FlashLlama(

  File "/opt/conda/lib/python3.9/site-packages/lorax_server/models/flash_llama.py", line 92, in __init__
    model = FlashLlamaForCausalLM(config, weights)

  File "/opt/conda/lib/python3.9/site-packages/lorax_server/models/custom_modeling/flash_llama_modeling.py", line 502, in __init__
    self.model = FlashLlamaModel(config, weights)

  File "/opt/conda/lib/python3.9/site-packages/lorax_server/models/custom_modeling/flash_llama_modeling.py", line 438, in __init__
    [

  File "/opt/conda/lib/python3.9/site-packages/lorax_server/models/custom_modeling/flash_llama_modeling.py", line 439, in <listcomp>
    FlashLlamaLayer(

  File "/opt/conda/lib/python3.9/site-packages/lorax_server/models/custom_modeling/flash_llama_modeling.py", line 373, in __init__
    self.self_attn = FlashLlamaAttention(

  File "/opt/conda/lib/python3.9/site-packages/lorax_server/models/custom_modeling/flash_llama_modeling.py", line 233, in __init__
    self.query_key_value = load_attention(config, prefix, weights, layer_id)

  File "/opt/conda/lib/python3.9/site-packages/lorax_server/models/custom_modeling/flash_llama_modeling.py", line 153, in load_attention
    base_layer = load_attention_multi(config, prefix, weights)

  File "/opt/conda/lib/python3.9/site-packages/lorax_server/models/custom_modeling/flash_llama_modeling.py", line 166, in load_attention_multi
    return TensorParallelColumnLinear.load_multi(

  File "/opt/conda/lib/python3.9/site-packages/lorax_server/utils/layers.py", line 333, in load_multi
    linear = get_linear(weight, bias, config.quantize)

  File "/opt/conda/lib/python3.9/site-packages/lorax_server/utils/layers.py", line 199, in get_linear
    linear = Linear4bit(

  File "/opt/conda/lib/python3.9/site-packages/lorax_server/utils/layers.py", line 152, in __init__
    self.weight = Params4bit(

NameError: name 'Params4bit' is not defined
 rank=0
2023-11-27T22:18:42.040335Z ERROR lorax_launcher: Shard 0 failed to start
2023-11-27T22:18:42.040380Z  INFO lorax_launcher: Shutting down shards```

**Comment by tgaddair** [comment]
#74
