### ISSUE TITLE
Error running Mixtral: 'TensorParallelHead' object has no attribute 'base_layer'

### ISSUE THREAD

**Issue by anjaliba2** [predibase/lorax#130]
### System Info

Running latest docker image

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

I started a mixtral server on 2 A100 (80GB) GPUs:
`lorax-launcher  --model-id mistralai/Mixtral-8x7B-Instruct-v0.1 --num-shard 2`

Then I sent a `generate_stream` request to `my_adapter`, which is an adapter trained with `target_modules= ["q_proj", "v_proj"]`.

I then get the following error:
```
2023-12-13T22:50:01.147514Z  INFO lorax_launcher: flash_causal_lm.py:742 Loading adapter weights into model: my_adater
2023-12-13T22:50:08.489110Z ERROR lorax_launcher: server.py:170 Error when loading adapter
Traceback (most recent call last):
  File "/opt/conda/bin/lorax-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.10/site-packages/lorax_server/cli.py", line 84, in serve
    server.serve(
  File "/opt/conda/lib/python3.10/site-packages/lorax_server/server.py", line 271, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/conda/lib/python3.10/site-packages/grpc_interceptor/server.py", line 165, in invoke_intercept_method
    return await self.intercept(
  File "/opt/conda/lib/python3.10/site-packages/lorax_server/interceptor.py", line 38, in intercept
    return await response
  File "/opt/conda/lib/python3.10/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 73, in _unary_interceptor
    return await behavior(request_or_iterator, context)
> File "/opt/conda/lib/python3.10/site-packages/lorax_server/server.py", line 162, in LoadAdapter
    self.model.load_adapter(adapter_id, adapter_source, adapter_index)
  File "/opt/conda/lib/python3.10/site-packages/lorax_server/models/flash_causal_lm.py", line 750, in load_adapter
    self.load_batched_adapter_weights(
  File "/opt/conda/lib/python3.10/site-packages/lorax_server/models/flash_causal_lm.py", line 796, in load_batched_adapter_weights
    base_weight = layer.base_layer.linear.weight
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'TensorParallelHead' object has no attribute 'base_layer'
```

Given the merged Mixtral pull request, I assumed that the model would be supported. Does this only apply to the base model or are adapters also supported?

### Expected behavior

I would expect the model to return a text response

**Comment by tgaddair** [comment]
Hey @anjaliba2, thanks for reporting and apologies about the bug. That was an oversight on my part. I have a fix up in #131 that should address the issue.

I haven't yet found a good adapter to test Mixtral with, which is why the error wasn't caught before. If you have a public adapter you've been testing I'd be happy to test it out. Otherwise, we can land it as is, the PR is pretty low risk.

**Comment by anjaliba2** [comment]
Wow, thanks so much for the quick fix! Let me quickly upload an adapter for testing purposes, I'll link it here :)

**Comment by anjaliba2** [comment]
@tgaddair uploaded an adapter here: https://huggingface.co/anjaliba2/mixtral-test/tree/main

**Comment by tgaddair** [comment]
Thanks @anjaliba2, glad I asked, as there were a couple other things that needed to be updated!

I've tested the PR end to end now and everything seems to be working, so I'll land it shortly. There's some delay in the Docker image builder at the moment, but that should hopefully be resolved soon and we should have a new image out later tonight.

**Comment by anjaliba2** [comment]
perfect, thanks so much!

**Comment by tgaddair** [comment]
New Docker image is up, let me know if you run into any issues!

**Comment by anjaliba2** [comment]
thanks a lot, will do!

**Comment by anjaliba2** [comment]
@tgaddair Is the image up under another tag? This might be my mistake too, but the error still occured when pulling and running ghcr.io/predibase/lorax:latest. I've also run the container in interactive mode and took a look at the code. The changes you made in the commits that fix the issue were not present there

**Comment by tgaddair** [comment]
Hey @anjaliba2, my mistake, it looks like the Docker build failed again. I'll let you know when that's fixed.

**Comment by tgaddair** [comment]
Hey @anjaliba2, thanks for your patience, this time for real the image appears to have been built and pushed:

```
docker pull ghcr.io/predibase/lorax:3ad7aae
```
