### ISSUE TITLE
CUDA error when for sgmv_lora_b for LM_head with many concurrent requests

### ISSUE THREAD

**Issue by tgaddair** [predibase/lorax#163]
It seems that if the server is flooded with requests for a new adapter it needs to download, a race condition can arise leading to CUDA errors. Needs more investigation.

**Comment by tgaddair** [comment]
Hmm, nevermind, this may be specific to the adapter.

**Comment by tgaddair** [comment]
Still, it is curious that even with `CUDA_LAUNCH_BLOCKING=1` we see an error here:

```
  File "/data/lorax/server/lorax_server/cli.py", line 85, in serve                                                                                                                
    server.serve(                                                                                                                                                                 
  File "/data/lorax/server/lorax_server/server.py", line 279, in serve                                                                                                            
    asyncio.run(                                                                                                                                                                  
  File "/opt/conda/lib/python3.10/asyncio/runners.py", line 44, in run                                                                                                            
    return loop.run_until_complete(main)                                                                                                                                          
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete                                                                                        
    self.run_forever()                                                                                                                                                            
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 603, in run_forever                                                                                               
    self._run_once()                                                                                                                                                              
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once                                                                                                
    handle._run()                                                                                                                                                                 
  File "/opt/conda/lib/python3.10/asyncio/events.py", line 80, in _run                                                                                                            
    self._context.run(self._callback, *self._args)                                                                                                                                
  File "/opt/conda/lib/python3.10/site-packages/grpc_interceptor/server.py", line 165, in invoke_intercept_method                                                                 
    return await self.intercept(                                                                                                                                                  
> File "/data/lorax/server/lorax_server/interceptor.py", line 38, in intercept                                                                                                    
    return await response                                                                                                                                                         
  File "/opt/conda/lib/python3.10/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 82, in _unary_interceptor                                                
    raise error                                                                                                                                                                   
  File "/opt/conda/lib/python3.10/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 73, in _unary_interceptor                                                
    return await behavior(request_or_iterator, context)                                                                                                                           
  File "/data/lorax/server/lorax_server/server.py", line 81, in Prefill                                                                                                           
    batch = self.model.batch_type.from_pb(                                                                                                                                        
  File "/data/lorax/server/lorax_server/models/flash_mistral.py", line 202, in from_pb                                                                                            
    adapter_indices = torch.cat(adapter_indices_list).to(dtype=torch.int64, device=device)                                                                                        
RuntimeError: CUDA error: an illegal memory access was encountered                                                                                                                
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

This would seem to suggest that the adapter index isn't set correctly.

**Comment by tgaddair** [comment]
Okay, seems this error occurs because a previous SGMV call failed. Must be something that isn't getting cleaned up properly.

**Comment by tgaddair** [comment]
Problem seems related to the LM head:

```
layer lm_head rank 64                                                                                                                                                             
lora_b_sgmv_cutlass 
- y=torch.Size([85, 32000]) 
- v=torch.Size([85, 64]) 
- tmp=torch.Size([60]) 
- wb_ptr=torch.Size([1])
- s_start=torch.Size([1]) 
- s_end=torch.Size([1]) 
- layer_idx=0                                               

segments 
- s_start=tensor([0], device='cuda:0', dtype=torch.int32) 
- s_end=tensor([4165], device='cuda:0', dtype=torch.int32) 0
```

**Comment by tgaddair** [comment]
Adapters:

```
base_model.model.lm_head.lora_A.weight torch.Size([64, 4096])
base_model.model.lm_head.lora_B.weight torch.Size([32000, 64])
```

**Comment by tgaddair** [comment]
Repro adapter: `FelixChao/Mistral-7b-Chem-TW-Lora`

**Comment by ajtejankar** [comment]
Here's the full stack trace with `CUDA_LAUNCH_BLOCKING=1`

```
sgmv_cutlass gemm.run failed: Error Internal
interceptor.py:41 Method Prefill encountered an error.
Traceback (most recent call last):
  File "/usr/src/lorax/server/lorax_server/cli.py", line 164, in <module>
    app()
  File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/usr/src/lorax/server/lorax_server/cli.py", line 83, in serve
    server.serve(
  File "/usr/src/lorax/server/lorax_server/server.py", line 309, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/conda/lib/python3.10/site-packages/grpc_interceptor/server.py", line 165, in invoke_intercept_method
    return await self.intercept(
> File "/usr/src/lorax/server/lorax_server/interceptor.py", line 38, in intercept
    return await response
  File "/opt/conda/lib/python3.10/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 82, in _unary_interceptor
    raise error
  File "/opt/conda/lib/python3.10/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 73, in _unary_interceptor
    return await behavior(request_or_iterator, context)
  File "/usr/src/lorax/server/lorax_server/server.py", line 90, in Prefill
    generations, next_batch = self.model.generate_token(batch)
  File "/opt/conda/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/src/lorax/server/lorax_server/models/flash_causal_lm.py", line 956, in generate_token
    out, speculative_logits = self._try_generate_token(batch, adapter_data)
  File "/usr/src/lorax/server/lorax_server/models/flash_causal_lm.py", line 915, in _try_generate_token
    raise e
  File "/usr/src/lorax/server/lorax_server/models/flash_causal_lm.py", line 912, in _try_generate_token
    return self.forward(batch, adapter_data)
  File "/usr/src/lorax/server/lorax_server/models/flash_causal_lm.py", line 891, in forward
    logits = model.forward(
  File "/usr/src/lorax/server/lorax_server/models/custom_modeling/flash_mistral_modeling.py", line 591, in forward
    logits, speculative_logits = self.lm_head(hidden_states, adapter_data)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/src/lorax/server/lorax_server/utils/layers.py", line 699, in forward
    logits = super().forward(input, adapter_data)
  File "/usr/src/lorax/server/lorax_server/utils/layers.py", line 662, in forward
    self.forward_layer_type(result, input, adapter_data, self.layer_name, start_idx, end_idx)
  File "/usr/src/lorax/server/lorax_server/utils/layers.py", line 548, in forward_layer_type
    lora_b_sgmv_cutlass(
  File "/usr/src/lorax/server/lorax_server/utils/sgmv.py", line 183, in lora_b_sgmv_cutlass
    _kernels.sgmv_cutlass(y, v, wb_ptr, s_start, s_end, tmp, layer_idx)
RuntimeError: No suitable kernel. dtype=Half
interceptor.py:41 Method ClearCache encountered an error.
Traceback (most recent call last):
  File "/usr/src/lorax/server/lorax_server/cli.py", line 164, in <module>
    app()
  File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/usr/src/lorax/server/lorax_server/cli.py", line 83, in serve
    server.serve(
  File "/usr/src/lorax/server/lorax_server/server.py", line 309, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/conda/lib/python3.10/site-packages/grpc_interceptor/server.py", line 165, in invoke_intercept_method
    return await self.intercept(
> File "/usr/src/lorax/server/lorax_server/interceptor.py", line 38, in intercept
    return await response
  File "/opt/conda/lib/python3.10/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 82, in _unary_interceptor
    raise error
  File "/opt/conda/lib/python3.10/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 73, in _unary_interceptor
    return await behavior(request_or_iterator, context)
  File "/usr/src/lorax/server/lorax_server/server.py", line 55, in ClearCache
    self.cache.delete(request.id)
  File "/usr/src/lorax/server/lorax_server/cache.py", line 40, in delete
    torch.cuda.empty_cache()
  File "/opt/conda/lib/python3.10/site-packages/torch/cuda/memory.py", line 162, in empty_cache
    torch._C._cuda_emptyCache()
RuntimeError: CUDA error: an illegal memory access was encountered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```
