### ISSUE TITLE
Not to able to serve mistralai/Mixtral-8x7B-Instruct-v0.1 on loraX with multiple GPU's

### ISSUE THREAD

**Issue by abhibst** [predibase/lorax#191]
### System Info

model="mistralai/Mixtral-8x7B-Instruct-v0.1"
volume="/data"
num_shard=4
sudo docker run --gpus all --shm-size 1g -p 8080:80 -v $volume:/data ghcr.io/predibase/lorax:latest --model-id $model --num-shard $num_shard --max-total-tokens 16000 --max-input-length 15999 --max-batch-prefill-tokens 15999 --quantize bitsandbytes

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

run the above docker cmd produce this error:

```
 File "/opt/conda/lib/python3.9/site-packages/lorax_server/server.py", line 214, in serve_inner
    model = get_model(
  File "/opt/conda/lib/python3.9/site-packages/lorax_server/models/__init__.py", line 304, in get_model
    raise ValueError("sharded is not supported for AutoModel")
ValueError: sharded is not supported for AutoModel
```

### Expected behavior

it should serve model as expected

**Comment by tgaddair** [comment]
Hey @abhibst, this error suggests that flash attention was unable to load in your environment. There should be an error message about it further up in the logs if you could share it. What type of GPU are you running on?

**Comment by abhibisht89** [comment]
this is the complete log:
```
2024-01-19T10:44:06.571077Z  INFO download: lorax_launcher: Successfully downloaded weights.
2024-01-19T10:44:06.571412Z  INFO shard-manager: lorax_launcher: Starting shard rank=0
2024-01-19T10:44:06.571497Z  INFO shard-manager: lorax_launcher: Starting shard rank=1
2024-01-19T10:44:06.572410Z  INFO shard-manager: lorax_launcher: Starting shard rank=2
2024-01-19T10:44:06.572613Z  INFO shard-manager: lorax_launcher: Starting shard rank=3
2024-01-19T10:44:10.713072Z ERROR lorax_launcher: server.py:218 Error when initializing model
Traceback (most recent call last):
  File "/opt/conda/bin/lorax-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.9/site-packages/lorax_server/cli.py", line 81, in serve
    server.serve(
  File "/opt/conda/lib/python3.9/site-packages/lorax_server/server.py", line 262, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "/opt/conda/lib/python3.9/site-packages/lorax_server/server.py", line 214, in serve_inner
    model = get_model(
  File "/opt/conda/lib/python3.9/site-packages/lorax_server/models/__init__.py", line 304, in get_model
    raise ValueError("sharded is not supported for AutoModel")
ValueError: sharded is not supported for AutoModel
```

**Comment by abhibisht89** [comment]
I am running it on 4 X A10 GPU

**Comment by abhibst** [comment]
I am running it on 4 X A10 GPU

this is the complete log:

```
2024-01-19T10:44:06.571077Z  INFO download: lorax_launcher: Successfully downloaded weights.
2024-01-19T10:44:06.571412Z  INFO shard-manager: lorax_launcher: Starting shard rank=0
2024-01-19T10:44:06.571497Z  INFO shard-manager: lorax_launcher: Starting shard rank=1
2024-01-19T10:44:06.572410Z  INFO shard-manager: lorax_launcher: Starting shard rank=2
2024-01-19T10:44:06.572613Z  INFO shard-manager: lorax_launcher: Starting shard rank=3
2024-01-19T10:44:10.713072Z ERROR lorax_launcher: server.py:218 Error when initializing model
Traceback (most recent call last):
  File "/opt/conda/bin/lorax-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.9/site-packages/lorax_server/cli.py", line 81, in serve
    server.serve(
  File "/opt/conda/lib/python3.9/site-packages/lorax_server/server.py", line 262, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "/opt/conda/lib/python3.9/site-packages/lorax_server/server.py", line 214, in serve_inner
    model = get_model(
  File "/opt/conda/lib/python3.9/site-packages/lorax_server/models/__init__.py", line 304, in get_model
    raise ValueError("sharded is not supported for AutoModel")
ValueError: sharded is not supported for AutoModel
```

**Comment by abhibst** [comment]
just providing more evidences , on TGI i do see this warning at the same stage , afterward it works there  : 

`2024-01-16T11:12:07.235138Z  WARN text_generation_launcher: Disabling exllama v2 and using v1 instead because there are issues when sharding`

**Comment by abhibst** [comment]
Any response on this . Thanks a lot for loraX 🤗

**Comment by tgaddair** [comment]
Hey @abhibst, sorry for the delay, let me try and repro quickly.

**Comment by tgaddair** [comment]
I wasn't able to repro the issue, so my suspicion is that there's an environment related issue that's being swallowed somehow. Let me try making some changes to the fallback logic here. In general, I don't think we should be falling back to AutoModel for officially supported model architectures.

**Comment by tgaddair** [comment]
Hmm, it looks like this code path shouldn't be hit it all, actually. My suspicion is your version of LoRAX may be a bit behind. Can you try running `docker pull ghcr.io/predibase/lorax:latest` to update to the most recent version?

**Comment by abhibst** [comment]
Thanks @tgaddair for all the help . Appreciated it  .

**Comment by rbollampally** [comment]
I'm not sure if this is related but with the latest and yesterday's nightly, I get the following:

Command to run:

`docker run --gpus all --env CUDA_VISIBLE_DEVICES=0,1,2,3 --shm-size 2g -p 8080:80 -v /home/ubuntu/Models:/data  ghcr.io/predibase/lorax:latest --model-id /data/Mixtral-8x7B-Instruct-v0.1/
`

Result:
```

2024-01-23T21:23:25.213706Z  INFO lorax_launcher: Args { model_id: "/data/Mixtral-8x7B-Instruct-v0.1/", adapter_id: "", source: "hub", adapter_source: "hub", revision: None, validation_workers: 2, sharded: None, num_shard: None, quantize: None, compile: false, dtype: None, trust_remote_code: false, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_input_length: 1024, max_total_tokens: 2048, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 4096, max_batch_total_tokens: None, max_waiting_tokens: 20, max_active_adapters: 128, adapter_cycle_time_s: 2, hostname: "12e2f11f8176", port: 80, shard_uds_path: "/tmp/lorax-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: Some("/data"), weights_cache_override: None, disable_custom_kernels: false, cuda_memory_fraction: 1.0, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_edge: None, env: false, download_only: false }
2024-01-23T21:23:25.213740Z  INFO lorax_launcher: Sharding model on 4 processes
2024-01-23T21:23:25.213839Z  INFO download: lorax_launcher: Starting download process.
2024-01-23T21:23:29.133843Z  INFO lorax_launcher: cli.py:105 Files are already present on the host. Skipping download.

2024-01-23T21:23:29.917630Z  INFO download: lorax_launcher: Successfully downloaded weights.
2024-01-23T21:23:29.917988Z  INFO shard-manager: lorax_launcher: Starting shard rank=0
2024-01-23T21:23:29.918070Z  INFO shard-manager: lorax_launcher: Starting shard rank=1
2024-01-23T21:23:29.918512Z  INFO shard-manager: lorax_launcher: Starting shard rank=2
2024-01-23T21:23:29.918563Z  INFO shard-manager: lorax_launcher: Starting shard rank=3
2024-01-23T21:23:39.926642Z  INFO shard-manager: lorax_launcher: Waiting for shard to be ready... rank=0
2024-01-23T21:23:39.926790Z  INFO shard-manager: lorax_launcher: Waiting for shard to be ready... rank=2
2024-01-23T21:23:39.927081Z  INFO shard-manager: lorax_launcher: Waiting for shard to be ready... rank=1
2024-01-23T21:23:39.928171Z  INFO shard-manager: lorax_launcher: Waiting for shard to be ready... rank=3
2024-01-23T21:23:49.933035Z  INFO shard-manager: lorax_launcher: Waiting for shard to be ready... rank=2
2024-01-23T21:23:49.933943Z  INFO shard-manager: lorax_launcher: Waiting for shard to be ready... rank=0
2024-01-23T21:23:49.934509Z  INFO shard-manager: lorax_launcher: Waiting for shard to be ready... rank=1
2024-01-23T21:23:49.935117Z  INFO shard-manager: lorax_launcher: Waiting for shard to be ready... rank=3
2024-01-23T21:23:59.939285Z  INFO shard-manager: lorax_launcher: Waiting for shard to be ready... rank=2
2024-01-23T21:23:59.940983Z  INFO shard-manager: lorax_launcher: Waiting for shard to be ready... rank=0
2024-01-23T21:23:59.941409Z  INFO shard-manager: lorax_launcher: Waiting for shard to be ready... rank=1
2024-01-23T21:23:59.942066Z  INFO shard-manager: lorax_launcher: Waiting for shard to be ready... rank=3
2024-01-23T21:24:09.945478Z  INFO shard-manager: lorax_launcher: Waiting for shard to be ready... rank=2
2024-01-23T21:24:09.947241Z  INFO shard-manager: lorax_launcher: Waiting for shard to be ready... rank=0
2024-01-23T21:24:09.947710Z  INFO shard-manager: lorax_launcher: Waiting for shard to be ready... rank=1
2024-01-23T21:24:09.948997Z  INFO shard-manager: lorax_launcher: Waiting for shard to be ready... rank=3
2024-01-23T21:24:19.951664Z  INFO shard-manager: lorax_launcher: Waiting for shard to be ready... rank=2
2024-01-23T21:24:19.953488Z  INFO shard-manager: lorax_launcher: Waiting for shard to be ready... rank=0
2024-01-23T21:24:19.954012Z  INFO shard-manager: lorax_launcher: Waiting for shard to be ready... rank=1
2024-01-23T21:24:19.955902Z  INFO shard-manager: lorax_launcher: Waiting for shard to be ready... rank=3
2024-01-23T21:24:29.957872Z  INFO shard-manager: lorax_launcher: Waiting for shard to be ready... rank=2
2024-01-23T21:24:29.959744Z  INFO shard-manager: lorax_launcher: Waiting for shard to be ready... rank=0
2024-01-23T21:24:29.960324Z  INFO shard-manager: lorax_launcher: Waiting for shard to be ready... rank=1
2024-01-23T21:24:29.962778Z  INFO shard-manager: lorax_launcher: Waiting for shard to be ready... rank=3
2024-01-23T21:24:36.967969Z ERROR shard-manager: lorax_launcher: Shard complete standard error output:

[E ProcessGroupNCCL.cpp:475] [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=60000) ran for 60328 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:489] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:495] To avoid data inconsistency, we are taking the entire process down.
[E ProcessGroupNCCL.cpp:916] [Rank 3] NCCL watchdog thread terminated with exception: [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=60000) ran for 60328 milliseconds before timing out.
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Rank 3] NCCL watchdog thread terminated with exception: [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=60000) ran for 60328 milliseconds before timing out. rank=3
2024-01-23T21:24:36.968009Z ERROR shard-manager: lorax_launcher: Shard process was signaled to shutdown with signal 6 rank=3
2024-01-23T21:24:37.059023Z ERROR lorax_launcher: Shard 3 failed to start
2024-01-23T21:24:37.059052Z  INFO lorax_launcher: Shutting down shards
2024-01-23T21:24:37.062720Z ERROR shard-manager: lorax_launcher: Shard complete standard error output:

[E ProcessGroupNCCL.cpp:475] [Rank 2] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=60000) ran for 60329 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:489] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:495] To avoid data inconsistency, we are taking the entire process down.
[E ProcessGroupNCCL.cpp:916] [Rank 2] NCCL watchdog thread terminated with exception: [Rank 2] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=60000) ran for 60329 milliseconds before timing out.
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Rank 2] NCCL watchdog thread terminated with exception: [Rank 2] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=60000) ran for 60329 milliseconds before timing out. rank=2
2024-01-23T21:24:37.062765Z ERROR shard-manager: lorax_launcher: Shard process was signaled to shutdown with signal 6 rank=2
2024-01-23T21:24:37.087817Z  INFO shard-manager: lorax_launcher: Shard terminated rank=1
2024-01-23T21:24:37.234983Z  INFO shard-manager: lorax_launcher: Shard terminated rank=0
Error: ShardCannotStart

```

**Comment by tgaddair** [comment]
Hey @rbollampally, thanks for reporting. Looks like one of the shards failed to start. Let me see if there might be something that changed recently on our side. Do you happen to know which Docker image you were on when this last worked for you?

**Comment by rbollampally** [comment]
I only started using it yesterday. Mistral worked without issues.

**Comment by abhibst** [comment]
I am able to run it , it is an issue with my older image . I pull the latest image and all works . Thanks a lot @tgaddair 
#loraX

**Comment by rbollampally** [comment]
@tgaddair My issue seems to be related to NVLINK. I added additional env variables to docker command and it works for me too. 

`docker run -e NCCL_P2P_LEVEL=NVL --gpus all --name lorax --shm-size 1g -p 8080:80 -v /home/ubuntu/Models:/data ghcr.io/predibase/lorax:latest --model-id /data/Mixtral-8x7B-Instruct-v0.1/ --dtype float16 --num-shard=4`

**Comment by tgaddair** [comment]
Thanks for sharing this info @rbollampally! This will be very helpful to other users running in the same issue.
