### ISSUE TITLE
Null adapter_config.base_model_name_or_path could result in downloading model failure

### ISSUE THREAD

**Issue by thincal** [predibase/lorax#315]
### System Info

- lorax v0.8.1
- `adapter_config.json` for LoRA weights
```
{
  "alpha_pattern": {},
  "auto_mapping": null,
  "base_model_name_or_path": null,
  ...
}
```

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

1. Initiate an inference request with a local adapter
- adapter_source="local"
- adapter_id="/path/to/local/adapter/dir"

2. Error happened in lorax server side
```
2024-03-08T17:03:38.057488Z  INFO lorax_router::loader: router/src/loader.rs:150: adapter local:/path/to/local/adapter/dir downloaded
2024-03-08T17:03:38.057519Z  INFO lorax_router::queue: router/src/queue.rs:135: set adapter local:/path/to/local/adapter/dir status to Downloaded
2024-03-08T17:03:38.059417Z  INFO lorax_launcher: model.py:168 Loading adapter weights into model: /path/to/local/adapter/dir

2024-03-08T17:03:38.064104Z  INFO lorax_launcher: model.py:168 Loading adapter weights into model: /path/to/local/adapter/dir

2024-03-08T17:03:38.066584Z  INFO lorax_launcher: model.py:168 Loading adapter weights into model: /path/to/local/adapter/dir

...

Traceback (most recent call last):
  ...

  File "/opt/conda/lib/python3.10/site-packages/lorax_server/cli.py", line 89, in serve
    server.serve(
  File "/opt/conda/lib/python3.10/site-packages/lorax_server/server.py", line 299, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/conda/lib/python3.10/site-packages/grpc_interceptor/server.py", line 165, in invoke_intercept_method
    return await self.intercept(
  File "/opt/conda/lib/python3.10/site-packages/lorax_server/interceptor.py", line 38, in intercept
    return await response
  File "/opt/conda/lib/python3.10/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 73, in _unary_interceptor
    return await behavior(request_or_iterator, context)
> File "/opt/conda/lib/python3.10/site-packages/lorax_server/server.py", line 191, in LoadAdapter
    self.model.load_adapter(adapter_parameters, adapter_source, adapter_index, api_token)
  File "/opt/conda/lib/python3.10/site-packages/lorax_server/models/model.py", line 170, in load_adapter
    module_map, adapter_config, adapter_weight_names, adapter_tokenizer = load_and_merge_adapters(
  File "/opt/conda/lib/python3.10/site-packages/lorax_server/utils/adapter.py", line 55, in load_and_merge_adapters
    return load_module_map(
  File "/opt/conda/lib/python3.10/site-packages/lorax_server/utils/adapter.py", line 111, in load_module_map
    model_config = AutoConfig.from_pretrained(adapter_config.base_model_name_or_path)
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1111, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/transformers/configuration_utils.py", line 633, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/transformers/configuration_utils.py", line 688, in _get_config_dict
    resolved_config_file = cached_file(
  File "/opt/conda/lib/python3.10/site-packages/transformers/utils/hub.py", line 441, in cached_file
    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like None is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

...

2024-03-08T17:03:48.214903Z ERROR lorax_client: router/client/src/lib.rs:34: Server error: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like None is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.
2024-03-08T17:03:48.214928Z  INFO lorax_router::loader: router/src/loader.rs:206: FAILED loading adapter local:/path/to/local/adapter/dir
2024-03-08T17:03:48.214957Z  INFO lorax_router::queue: router/src/queue.rs:135: set adapter local:/path/to/local/adapter/dir status to Errored
2024-03-08T17:03:48.215044Z  INFO lorax_router::loader: router/src/loader.rs:276: terminating adapter local:/path/to/local/adapter/dir loader
```

### Expected behavior

Request is handled successfully.

**Comment by thincal** [comment]
A simple fix could be validating the `base_model_name_or_path` before compare with `adapter_id` (https://github.com/predibase/lorax/blob/v0.8.1/server/lorax_server/utils/adapter.py#L108), if this sounds reasonable, I will prepare a PR for review @tgaddair

**Comment by tgaddair** [comment]
Thanks for reporting this @thincal! Your proposed fix sounds reasonable to me. Thanks for offering to put together a PR!

**Comment by thincal** [comment]
It seems fixed by https://github.com/predibase/lorax/commit/e637d890cf1bb0d9a9c133e3c0b0464dedfd7c56
