### ISSUE TITLE
Server error: 'FlashQwen2ForCausalLM' object has no attribute 'transformer'

### ISSUE THREAD

**Issue by KrisWongz** [predibase/lorax#339]
### System Info

latest，2 A100 （40g）

### Information

- [ ] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

@tgaddair cool, thanks for the support. But I got an eorror when add an adatper:
> Traceback (most recent call last):
  File "/home/unionlab001/WangZe/WZ_test/lorax/test_lorax_qwen.py", line 20, in <module>
    print(client.generate(prompt, max_new_tokens=128, temperature=0.7, stop_sequences=["<|endoftext|>"], adapter_id=adapter_id,adapter_source=adapter_source).generated_text)
  File "/home/unionlab001/anaconda3/envs/llama_factory/lib/python3.10/site-packages/lorax/client.py", line 184, in generate
    raise parse_error(resp.status_code, payload)
lorax.errors.GenerationError: Request failed during generation: Server error: 'FlashQwen2ForCausalLM' object has no attribute 'transformer'

The details：
> 2024-03-19T09:17:58.037790Z ERROR lorax_launcher: interceptor.py:41 Method LoadAdapter encountered an error.
Traceback (most recent call last):
  File "/opt/conda/bin/lorax-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.10/site-packages/lorax_server/cli.py", line 89, in serve
    server.serve(
  File "/opt/conda/lib/python3.10/site-packages/lorax_server/server.py", line 317, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/conda/lib/python3.10/site-packages/grpc_interceptor/server.py", line 165, in invoke_intercept_method
    return await self.intercept(
> File "/opt/conda/lib/python3.10/site-packages/lorax_server/interceptor.py", line 38, in intercept
    return await response
  File "/opt/conda/lib/python3.10/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 82, in _unary_interceptor
    raise error
  File "/opt/conda/lib/python3.10/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 73, in _unary_interceptor
    return await behavior(request_or_iterator, context)
  File "/opt/conda/lib/python3.10/site-packages/lorax_server/server.py", line 205, in LoadAdapter
    self.model.load_adapter(adapter_parameters, adapter_source, adapter_index, api_token)
  File "/opt/conda/lib/python3.10/site-packages/lorax_server/models/model.py", line 184, in load_adapter
    self.load_batched_adapter_weights(
  File "/opt/conda/lib/python3.10/site-packages/lorax_server/models/model.py", line 225, in load_batched_adapter_weights
    nlayers = self.get_num_layers_for_type(layer_type)
  File "/opt/conda/lib/python3.10/site-packages/lorax_server/models/flash_qwen2.py", line 150, in get_num_layers_for_type
    return 1 if layer_type == LM_HEAD else len(self.model.transformer.h)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1688, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'FlashQwen2ForCausalLM' object has no attribute 'transformer'

2024-03-19T09:17:58.038447Z ERROR lorax_client: router/client/src/lib.rs:34: Server error: 'FlashQwen2ForCausalLM' object has no attribute 'transformer'
2024-03-19T09:17:58.038973Z ERROR lorax_client: router/client/src/lib.rs:34: Server error: 'FlashQwen2ForCausalLM' object has no attribute 'transformer'
2024-03-19T09:17:58.038990Z  INFO lorax_router::loader: router/src/loader.rs:207: FAILED loading adapter local:/data/240315-3-epoch-256-yingxiao_req1_2_similar_and_real_labels
2024-03-19T09:17:58.039006Z  INFO lorax_router::queue: router/src/queue.rs:139: set adapter local:/data/240315-3-epoch-256-yingxiao_req1_2_similar_and_real_labels status to Errored
2024-03-19T09:17:58.039071Z  INFO lorax_router::loader: router/src/loader.rs:277: terminating adapter local:/data/240315-3-epoch-256-yingxiao_req1_2_similar_and_real_labels loader

My code：
> adapter_id = "/data/240315-3-epoch-256-yingxiao_req1_2_similar_and_real_labels"   # 调用的lora微调模型地址
adapter_source="local"
print(client.generate(prompt, max_new_tokens=128, temperature=0.7, stop_sequences=["<|endoftext|>"], adapter_id=adapter_id,adapter_source=adapter_source).generated_text)

.sh:
> docker run --gpus '"device=1,2"'  \
    --shm-size 1g \
    -p 8081:80 \
    -v /home/Model/qwen:/data ghcr.io/predibase/lorax:latest \
    --model-id /data/Qwen1_5-14B-Chat \
    --trust-remote-code \
    --max-batch-prefill-tokens 1024 \
    --num-shard 2 \

My environment: 2 A100 40g 

### Expected behavior

none

**Comment by KrisWongz** [comment]
In addition, there is something different after I pulled the latest docker. An A100 40G cannot run qwen1.5-14b-chat, but it was possible before. I set --max-batch-prefill-tokens from 4096 to 1024 still can't work.
> 2024-03-19T09:54:39.063000Z ERROR lorax_launcher: interceptor.py:41 Method Warmup encountered an error.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/lorax_server/models/flash_causal_lm.py", line 775, in warmup
    cache_manager = set_cache_manager(
  File "/opt/conda/lib/python3.10/site-packages/lorax_server/models/cache_manager.py", line 124, in set_cache_manager
    CACHE_MANAGER = CacheManager(
  File "/opt/conda/lib/python3.10/site-packages/lorax_server/models/cache_manager.py", line 29, in __init__
    self.kv_cache = [
  File "/opt/conda/lib/python3.10/site-packages/lorax_server/models/cache_manager.py", line 31, in <listcomp>
    torch.empty(
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 320.00 MiB. GPU 0 has a total capacity of 39.39 GiB of which 197.62 MiB is free. Including non-PyTorch memory, this process has 0 bytes memory in use. Of the allocated memory 38.61 GiB is allocated by PyTorch, and 103.69 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/opt/conda/bin/lorax-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.10/site-packages/lorax_server/cli.py", line 89, in serve
    server.serve(
  File "/opt/conda/lib/python3.10/site-packages/lorax_server/server.py", line 317, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/conda/lib/python3.10/site-packages/grpc_interceptor/server.py", line 165, in invoke_intercept_method
    return await self.intercept(
> File "/opt/conda/lib/python3.10/site-packages/lorax_server/interceptor.py", line 38, in intercept
    return await response
  File "/opt/conda/lib/python3.10/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 82, in _unary_interceptor
    raise error
  File "/opt/conda/lib/python3.10/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 73, in _unary_interceptor
    return await behavior(request_or_iterator, context)
  File "/opt/conda/lib/python3.10/site-packages/lorax_server/server.py", line 80, in Warmup
    max_supported_total_tokens = self.model.warmup(batch, request.max_new_tokens)
  File "/opt/conda/lib/python3.10/site-packages/lorax_server/models/flash_causal_lm.py", line 791, in warmup
    raise RuntimeError(
RuntimeError: Not enough memory to handle 1024 prefill tokens. You need to decrease `--max-batch-prefill-tokens`
2024-03-19T09:54:39.074548Z ERROR warmup{max_input_length=1024 max_prefill_tokens=1024 max_total_tokens=2048}:warmup: lorax_client: router/client/src/lib.rs:34: Server error: Not enough memory to handle 1024 prefill tokens. You need to decrease `--max-batch-prefill-tokens`
Error: Warmup(Generation("Not enough memory to handle 1024 prefill tokens. You need to decrease `--max-batch-prefill-tokens`"))
2024-03-19T09:54:39.138360Z ERROR lorax_launcher: Webserver Crashed
2024-03-19T09:54:39.138380Z  INFO lorax_launcher: Shutting down shards
2024-03-19T09:54:39.142818Z  INFO shard-manager: lorax_launcher: Shard terminated rank=0
Error: WebserverFailed

**Comment by tgaddair** [comment]
Hey @KrisWongz, thanks for reporting this issue. This bug came about as I haven't been able to test the Qwen2 LoRA loading yet (need to find a public Qwen2 LoRA to test out). But this was a quick fix. It should be addressed by PR #345.

For the second issue, I'm not sure what might have changed to cause that at first glance. Is it possible there is another process using GPU memory? Can you check that the GPU is free before starting LoRAX with `nvidia-smi`?

**Comment by KrisWongz** [comment]
> Hey @KrisWongz, thanks for reporting this issue. This bug came about as I haven't been able to test the Qwen2 LoRA loading yet (need to find a public Qwen2 LoRA to test out). But this was a quick fix. It should be addressed by PR #345.
> 
> For the second issue, I'm not sure what might have changed to cause that at first glance. Is it possible there is another process using GPU memory? Can you check that the GPU is free before starting LoRAX with `nvidia-smi`?

@tgadair Thanks a lot.
I'm sure the GPU is empty.
<img width="618" alt="image" src="https://github.com/predibase/lorax/assets/40886486/5b898d14-0c40-41cd-a23c-9ce9973f019e">
The code:
> docker run --gpus '"device=1"'  \
    --shm-size 1g \
    -p 8081:80 \
    -v /home/Model/qwen:/data ghcr.io/predibase/lorax:latest \
    --model-id /data/Qwen1_5-14B-Chat \
    --trust-remote-code \
    --max-batch-prefill-tokens 1024 \

The error:
>RuntimeError: Not enough memory to handle 1024 prefill tokens. You need to decrease `--max-batch-prefill-tokens`
2024-03-20T07:57:45.050465Z ERROR warmup{max_input_length=1024 max_prefill_tokens=1024 max_total_tokens=2048}:warmup: lorax_client: router/client/src/lib.rs:34: Server error: Not enough memory to handle 1024 prefill tokens. You need to decrease `--max-batch-prefill-tokens`
Error: Warmup(Generation("Not enough memory to handle 1024 prefill tokens. You need to decrease `--max-batch-prefill-tokens`"))
2024-03-20T07:57:45.117908Z ERROR lorax_launcher: Webserver Crashed
2024-03-20T07:57:45.117934Z  INFO lorax_launcher: Shutting down shards
2024-03-20T07:57:45.123286Z  INFO shard-manager: lorax_launcher: Shard terminated rank=0

Then I set it to 2 GPUs, but it used 70GB memery:
> docker run --gpus '"device=1,2"'  \
    --shm-size 1g \
    -p 8081:80 \
    -v /home/unionlab001/Model/qwen:/data ghcr.io/predibase/lorax:latest \
    --model-id /data/Qwen1_5-14B-Chat \
    --trust-remote-code \
    --max-batch-prefill-tokens 1024 \
    --num-shard 2 \

<img width="625" alt="image" src="https://github.com/predibase/lorax/assets/40886486/12837113-50af-4cf5-a76d-64990ae9bc9a">
