### ISSUE TITLE
Mistral model requires flash attention v2

### ISSUE THREAD

**Issue by pribadihcr** [predibase/lorax#42]
Hi 
I got the following error:
```
NotImplementedError: Mistral model requires flash attention v2
```

I tried use model=TheBloke/Mistral-7B-Instruct-v0.1-GPTQ

Thanks

**Comment by tgaddair** [comment]
Hey @pribadihcr, thanks for trying out LoRAX!

This error message can sometimes be misleading, was there any other error above in the logs that you can share? Also, are you running in our pre-built Docker images?

**Comment by pribadihcr** [comment]
Hi @tgaddair , here is the full logs

```
model=TheBloke/Mistral-7B-Instruct-v0.1-GPTQ

docker run --gpus all --shm-size 1g -p 8080:80 -v $volume:/data -e HF_HUB_ENABLE_HF_TRANSFER=0 ghcr.io/predibase/lorax:latest --model-id $model



2023-11-17T02:38:15.469298Z  INFO lorax_launcher: Args { model_id: "TheBloke/Mistral-7B-Instruct-v0.1-GPTQ", adapter_id: "", source: "hub", adapter_source: "hub", revision: None, validation_workers: 2, sharded: None, num_shard: None, quantize: None, dtype: None, trust_remote_code: false, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_input_length: 1024, max_total_tokens: 2048, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 4096, max_batch_total_tokens: None, max_waiting_tokens: 20, hostname: "f5ab61aeb3c5", port: 80, shard_uds_path: "/tmp/lorax-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: Some("/data"), weights_cache_override: None, disable_custom_kernels: false, cuda_memory_fraction: 1.0, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_edge: None, env: false, download_only: false }
2023-11-17T02:38:15.469394Z  INFO download: lorax_launcher: Starting download process.
2023-11-17T02:38:18.625603Z  INFO lorax_launcher: hub.py:123 Download file: model.safetensors

2023-11-17T02:44:40.962134Z  INFO lorax_launcher: hub.py:131 Downloaded /data/models--TheBloke--Mistral-7B-Instruct-v0.1-GPTQ/snapshots/6ae1e4ae2cfbaf107c705ed722ec243b4f88014d/model.safetensors in 0:06:22.

2023-11-17T02:44:40.962245Z  INFO lorax_launcher: hub.py:153 Download: [1/1] -- ETA: 0

2023-11-17T02:44:41.505805Z  INFO download: lorax_launcher: Successfully downloaded weights.
2023-11-17T02:44:41.505949Z  INFO shard-manager: lorax_launcher: Starting shard rank=0
2023-11-17T02:44:43.908316Z  WARN lorax_launcher: flash_attn.py:48 Unable to use Flash Attention V2: GPU with CUDA capability 7 5 is not supported for Flash Attention V2

2023-11-17T02:44:43.911488Z  WARN lorax_launcher: __init__.py:73 Could not import Mistral model: Mistral model requires flash attn v2

2023-11-17T02:44:44.480708Z ERROR lorax_launcher: server.py:218 Error when initializing model
Traceback (most recent call last):
  File "/opt/conda/bin/lorax-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.9/site-packages/lorax_server/cli.py", line 81, in serve
    server.serve(
  File "/opt/conda/lib/python3.9/site-packages/lorax_server/server.py", line 262, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "/opt/conda/lib/python3.9/site-packages/lorax_server/server.py", line 214, in serve_inner
    model = get_model(
  File "/opt/conda/lib/python3.9/site-packages/lorax_server/models/__init__.py", line 283, in get_model
    raise NotImplementedError("Mistral model requires flash attention v2")
NotImplementedError: Mistral model requires flash attention v2

2023-11-17T02:44:44.910114Z ERROR shard-manager: lorax_launcher: Shard complete standard error output:

Downloading (…)lve/main/config.json: 100%|██████████| 963/963 [00:00<00:00, 46.9kB/s]
Traceback (most recent call last):

  File "/opt/conda/bin/lorax-server", line 8, in <module>
    sys.exit(app())

  File "/opt/conda/lib/python3.9/site-packages/lorax_server/cli.py", line 81, in serve
    server.serve(

  File "/opt/conda/lib/python3.9/site-packages/lorax_server/server.py", line 262, in serve
    asyncio.run(

  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)

  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()

  File "/opt/conda/lib/python3.9/site-packages/lorax_server/server.py", line 214, in serve_inner
    model = get_model(

  File "/opt/conda/lib/python3.9/site-packages/lorax_server/models/__init__.py", line 283, in get_model
    raise NotImplementedError("Mistral model requires flash attention v2")

NotImplementedError: Mistral model requires flash attention v2
 rank=0
Error: ShardCannotStart
2023-11-17T02:44:45.009297Z ERROR lorax_launcher: Shard 0 failed to start
2023-11-17T02:44:45.009346Z  INFO lorax_launcher: Shutting down shards

```

**Comment by tgaddair** [comment]
Thanks @pribadihcr, the key line is this one:

```
2023-11-17T02:44:43.908316Z  WARN lorax_launcher: flash_attn.py:48 Unable to use Flash Attention V2: GPU with CUDA capability 7 5 is not supported for Flash Attention V2
```

What type of GPU are you running on? Looks lik flash attention v2 requires Ampere (A10G, A100, etc.) and above.

**Comment by tgaddair** [comment]
Hey @pribadihcr, just wanted to follow-up on this.

**Comment by pribadihcr** [comment]
HI @tgaddair, Sorry. My GPU is poor ( GTX 2070 )  :(

**Comment by joaopcm1996** [comment]
Getting the same error with mistral 7b when deploying on A10G, base lorax container. Any workaround?

**Comment by tgaddair** [comment]
Hey @joaopcm1996, can you share the nvidia driver version you're using (output from `nvidia-smi`)? We haven't updated min driver version in some time, so this shouldn't be due to a change in the LoRAX image. I just put up PR #328 which should hopefully make the true error more apparent, however.

**Comment by joaopcm1996** [comment]
Turns out this was indeed a driver version issue, not on LoRAX. Thanks ! 

`NVIDIA-SMI 470.182.03 Driver Version: 470.182.03 CUDA Version: 12.1`

**Comment by tgaddair** [comment]
Thanks @joaopcm1996 for closing the loop!

**Comment by joaomsimoes** [comment]
Hi @joaopcm1996 I followed your tutorial that you posted on medium and I got stuck with the same problem. I'm trying to spin up a AWS Sagemaker Async endpoint and I get the same error:

```
ImportError: CUDA is not available
Shard complete standard error output:
The NVIDIA driver on your system is too old (found version 11080). Please update your GPU driver by downloading and installing a new version from the URL .........
The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit 
```
I'm also using an A10g.

My question is, how can you update the drivers on sagemaker? Or do I just build the docker image using a more recent cuda version?

**Comment by joaopcm1996** [comment]
Backing NVIDIA drivers into the container will not work, and it's not possible for a user to update the drivers on SageMaker endpoint instances. The solution until they are updated is to revert to LoRAX 0.8.0, worked for me.
