### ISSUE TITLE
Speculative tokens fails during warmup in some scenarios

### ISSUE THREAD

**Issue by tgaddair** [predibase/lorax#444]
Params:

```
--model-id meta-llama/Meta-Llama-3-70B
--speculative-tokens 3
--quantize bitsandbytes-nf4
--max-input-length 8000 
--max-total-tokens 8192 
--max-batch-prefill-tokens 8192
--sharded
```

```
Traceback (most recent call last):                                                                                                                                                                         
  File "/data/lorax/server/lorax_server/cli.py", line 164, in <module>                                                                                                                                     
    app()                                                                                                                                                                                                  
  File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 311, in __call__                                                                                                                      
    return get_command(self)(*args, **kwargs)                                                                                                                                                              
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1157, in __call__                                                                                                                     
    return self.main(*args, **kwargs)                                                                                                                                                                      
  File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 778, in main                                                                                                                          
    return _main(                                                                                                                                                                                          
  File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 216, in _main                                                                                                                         
    rv = self.invoke(ctx)                                                                                                                                                                                  
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1688, in invoke                                                                                                                       
    return _process_result(sub_ctx.command.invoke(sub_ctx))                                                                                                                                                
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1434, in invoke                                                                                                                       
    return ctx.invoke(self.callback, **ctx.params)                                                                                                                                                         
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 783, in invoke                                                                                                                        
    return __callback(*args, **kwargs)                                                                                                                                                                     
  File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 683, in wrapper                                                                                                                       
    return callback(**use_params)  # type: ignore                                                                                                                                                          
  File "/data/lorax/server/lorax_server/cli.py", line 83, in serve                                                                                                                                         
    server.serve(                                                                                                                                                                                          
  File "/data/lorax/server/lorax_server/server.py", line 309, in serve                                                                                                                                     
    asyncio.run(                                                                                                                                                                                           
  File "/opt/conda/lib/python3.10/asyncio/runners.py", line 44, in run                                                                                                                                     
    return loop.run_until_complete(main)                                                                                                                                                                   
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete                                                                                                                 
    self.run_forever()                                                                                                                                                                                     
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 603, in run_forever                                                                                                                        
    self._run_once()                                                                                                                                                                                       
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once                                                                                                                         
    handle._run()                                                                                                                                                                                          
  File "/opt/conda/lib/python3.10/asyncio/events.py", line 80, in _run                                                                                                                                     
    self._context.run(self._callback, *self._args)                                                                                                                                                         
  File "/opt/conda/lib/python3.10/site-packages/grpc_interceptor/server.py", line 165, in invoke_intercept_method                                                                                          
    return await self.intercept(                                                                                                                                                                           
> File "/data/lorax/server/lorax_server/interceptor.py", line 38, in intercept                                                                                                                             
    return await response                                                                                                                                                                                  
  File "/opt/conda/lib/python3.10/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 82, in _unary_interceptor                                                                         
    raise error                                                                                                                                                                                            
  File "/opt/conda/lib/python3.10/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 73, in _unary_interceptor                                                                         
    return await behavior(request_or_iterator, context)                                                                                                                                                    
  File "/data/lorax/server/lorax_server/server.py", line 77, in Warmup                                                                                                                                     
    max_supported_total_tokens = self.model.warmup(batch, request.max_new_tokens)                                                                                                                          
  File "/data/lorax/server/lorax_server/models/flash_causal_lm.py", line 770, in warmup                                                                                                                    
    _, batch = self.generate_token(batch, is_warmup=True)                                                                                                                                                  
  File "/opt/conda/lib/python3.10/contextlib.py", line 79, in inner                                                                                                                                        
    return func(*args, **kwds)                                                                                                                                                                             
  File "/data/lorax/server/lorax_server/models/flash_causal_lm.py", line 1062, in generate_token                                                                                                           
    batch.all_input_ids_tensor[i, input_length + j] = next_input_ids[idx]                                                                                                                                  
IndexError: index 8195 is out of bounds for dimension 1 with size 8195 
```

**Comment by tgaddair** [comment]
Fixed by #447.
