### ISSUE TITLE
Not able to load adapter from local dir

### ISSUE THREAD

**Issue by abhibst** [predibase/lorax#51]
### System Info

base model: meta-llama/Llama-2-13b-chat-hf

docker cmd:
docker run --gpus '"device=3"' --shm-size 1g -e HUGGING_FACE_HUB_TOKEN=XXXXX -p 8082:82 -v $volume:/data ghcr.io/predibase/lorax:latest --model-id $model --quantize bitsandbytes

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

```
from lorax import Client
URL="http://127.0.0.0:8082"
client = Client(URL,timeout=20)

adapter_id="./data/lora_models/unsighing/" #this dir contain adapter_config.json or adapter_model.bin
adapter_source="local"
client.generate(prompt,max_new_tokens=128,temperature=0.001,adapter_id=adapter_id,adapter_source=adapter_source).generated_text
```
getting this error while running the above code :
`GenerationError: Request failed during generation: Server error: No local weights found in ./data/lora_models/unsighing/ with extension .safetensors`

Also getting a different error while putting the complete path for adapter_id:
```
adapter_id="home/code/data/lora_models/unsighing/"

GenerationError: Request failed during generation: Server error: Can't find 'adapter_config.json' at 'home/code/data/lora_models/unsighing/'
```

**More info:**
**base model:** meta-llama/Llama-2-13b-chat-hf
**docker cmd:**
docker run --gpus '"device=3"' --shm-size 1g -e HUGGING_FACE_HUB_TOKEN=XXXXX -p 8082:82 -v $volume:/data ghcr.io/predibase/lorax:latest --model-id $model --quantize bitsandbytes

**Note**: I am able to do successful prediction out of base model , if i didn't provide adapter_id in the same above setup.

`client.generate(prompt,max_new_tokens=128,temperature=0.001).generated_text
`
This works good for me.

Any help will be appreciated, Thanks  

### Expected behavior

Should load the adapter from local dir.

**Comment by tgaddair** [comment]
Hey @abhibst, can you share the contents of `home/code/data/lora_models/unsighing/`? It may be the case that your local directory contains the adapter weights, but not the adapter config, which is needed to load the adapter metadata.

For example, here's the contents of an adapter directory I was successfully able to prompt locally:

```
$ ls ../models--vineetsharma--qlora-adapter-Mistral-7B-Instruct-v0.1-gsm8k

adapter_config.json  adapter_model.bin  adapter_model.safetensors
```

**Comment by abhibst** [comment]
@tgaddair 

<img width="775" alt="Screenshot 2023-11-21 at 20 45 36" src="https://github.com/predibase/lorax/assets/136707939/62ba6ed5-0830-42a3-a7a7-ba23db8c50df">

**Comment by tgaddair** [comment]
Thanks for verifying @abhibst, let me see if there's a bug on our side. Maybe we're making some bad assumptions about where the config file lives.

**Comment by tgaddair** [comment]
One other thing to try quickly, can you try running again with the leading `/` in the adapter ID?

```
adapter_id="/home/code/data/lora_models/unsighing"
```

**Comment by abhibst** [comment]
@tgaddair , Thanks for being so prompt on the issue

I did tried the above suggestions, here is my responses:

```
!ls -l /home/code/data/lora_models/unsighing/

total 220
-rwxrwxrwx 1 a.bisht a.bisht    440 Aug  9 09:05 README.md
-rwxrwxrwx 1 a.bisht a.bisht    452 Aug  9 09:05 adapter_config.json
-rwxrwxrwx 1 a.bisht a.bisht    443 Aug  9 09:05 adapter_model.bin
-rwxrwxrwx 1 a.bisht a.bisht    598 Aug  9 06:22 finetune_args.json
-rwxrwxrwx 1 a.bisht a.bisht    264 Aug  9 06:21 info.json
-rwxrwxrwx 1 a.bisht a.bisht 164896 Aug  9 06:21 train_data_samples.json
-rwxrwxrwx 1 a.bisht a.bisht    248 Aug  9 09:05 train_output.json
-rwxrwxrwx 1 a.bisht a.bisht   3337 Aug  9 06:22 trainer_args.json
-rwxrwxrwx 1 a.bisht a.bisht  25801 Aug  9 09:05 trainer_log_history.jsonl
```



```
import os
os.path.exists('/home/code/data/lora_models/unsighing/adapter_config.json')

**>>True**

this works well
```



```
from peft import LoraConfig
LoraConfig.from_pretrained('/home/code/data/lora_models/unsighing/adapter_config.json')

**output: ERROR**
---------------------------------------------------------------------------
HFValidationError                         Traceback (most recent call last)
File ~/miniconda3/envs/mytorch/lib/python3.9/site-packages/peft/utils/config.py:106, in PeftConfigMixin.from_pretrained(cls, pretrained_model_name_or_path, subfolder, **kwargs)
    105 try:
--> 106     config_file = hf_hub_download(pretrained_model_name_or_path, CONFIG_NAME, subfolder=subfolder)
    107 except Exception:

File ~/miniconda3/envs/mytorch/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py:110, in validate_hf_hub_args.<locals>._inner_fn(*args, **kwargs)
    109 if arg_name in ["repo_id", "from_id", "to_id"]:
--> 110     validate_repo_id(arg_value)
    112 elif arg_name == "token" and arg_value is not None:

File ~/miniconda3/envs/mytorch/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py:158, in validate_repo_id(repo_id)
    157 if repo_id.count("/") > 1:
--> 158     raise HFValidationError(
    159         "Repo id must be in the form 'repo_name' or 'namespace/repo_name':"
    160         f" '{repo_id}'. Use `repo_type` argument if needed."
    161     )
    163 if not REPO_ID_REGEX.match(repo_id):

HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/home/code/data/lora_models/unsighing/adapter_config.json'. Use `repo_type` argument if needed.

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
Cell In[71], line 1
----> 1 LoraConfig.from_pretrained('/home/code/data/lora_models/unsighing/adapter_config.json')

File ~/miniconda3/envs/mytorch/lib/python3.9/site-packages/peft/utils/config.py:108, in PeftConfigMixin.from_pretrained(cls, pretrained_model_name_or_path, subfolder, **kwargs)
    106         config_file = hf_hub_download(pretrained_model_name_or_path, CONFIG_NAME, subfolder=subfolder)
    107     except Exception:
--> 108         raise ValueError(f"Can't find '{CONFIG_NAME}' at '{pretrained_model_name_or_path}'")
    110 loaded_attributes = cls.from_json_file(config_file)
    112 config = cls(**kwargs)

ValueError: Can't find 'adapter_config.json' at '/home/code/data/lora_models/unsighing/adapter_config.json'
```



```
LoraConfig.from_pretrained('/home/code/data/lora_models/unsighing/')
**output: This works** 
LoraConfig(peft_type='LORA', base_model_name_or_path='meta-llama/Llama-2-13b-chat-hf', task_type='CAUSAL_LM', inference_mode=True, r=8, target_modules=['q_proj', 'v_proj'], lora_alpha=16, lora_dropout=0.05, fan_in_fan_out=False, bias='none', modules_to_save=None, init_lora_weights=True)
```

**Comment by tgaddair** [comment]
No problem, @abhibst, thanks for patience in debugging this!

I'm starting to wonder if I might be wrong about where the error message is coming from on the server side. Are you able to look at the server logs and share the stack trace that is printed out when you try using the local adapter?

**Comment by abhibst** [comment]
@tgaddair , here we go, server side logs:

```
2023-11-22T18:44:06.966765Z  INFO lorax_router::loader: router/src/loader.rs:135: adapter /home/code/data/lora_models/unsighing/ downloaded
2023-11-22T18:44:06.966803Z  INFO lorax_router::queue: router/src/queue.rs:125: set adapter /home/code/data/lora_models/unsighing/ status to Downloaded
2023-11-22T18:44:06.967832Z  INFO lorax_launcher: flash_causal_lm.py:761 Loading adapter weights into model: /home/code/data/lora_models/unsighing/

2023-11-22T18:44:06.969453Z ERROR lorax_launcher: server.py:161 Error when loading adapter
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/peft/utils/config.py", line 117, in from_pretrained
    config_file = hf_hub_download(
  File "/opt/conda/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 112, in _inner_fn
    validate_repo_id(arg_value)
  File "/opt/conda/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 160, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/home/code/data/lora_models/unsighing'. Use `repo_type` argument if needed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/lorax-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.9/site-packages/lorax_server/cli.py", line 81, in serve
    server.serve(
  File "/opt/conda/lib/python3.9/site-packages/lorax_server/server.py", line 262, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/conda/lib/python3.9/site-packages/grpc_interceptor/server.py", line 159, in invoke_intercept_method
    return await self.intercept(
  File "/opt/conda/lib/python3.9/site-packages/lorax_server/interceptor.py", line 21, in intercept
    return await response
  File "/opt/conda/lib/python3.9/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 73, in _unary_interceptor
    return await behavior(request_or_iterator, context)
> File "/opt/conda/lib/python3.9/site-packages/lorax_server/server.py", line 153, in LoadAdapter
    self.model.load_adapter(adapter_id, adapter_source, adapter_index)
  File "/opt/conda/lib/python3.9/site-packages/lorax_server/models/flash_causal_lm.py", line 763, in load_adapter
    module_map, adapter_config = load_module_map(self.model_id, adapter_id, adapter_source, weight_names)
  File "/opt/conda/lib/python3.9/site-packages/lorax_server/utils/adapter.py", line 28, in load_module_map
    adapter_config = LoraConfig.from_pretrained(config_path)
  File "/opt/conda/lib/python3.9/site-packages/peft/utils/config.py", line 121, in from_pretrained
    raise ValueError(f"Can't find '{CONFIG_NAME}' at '{pretrained_model_name_or_path}'")
ValueError: Can't find 'adapter_config.json' at '/home/code/data/lora_models/unsighing'

2023-11-22T18:44:06.969639Z ERROR lorax_client: router/client/src/lib.rs:33: Server error: Can't find 'adapter_config.json' at '/home/code/data/lora_models/unsighing'
2023-11-22T18:44:06.969964Z ERROR lorax_launcher: interceptor.py:24 Method LoadAdapter encountered an error.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/peft/utils/config.py", line 117, in from_pretrained
    config_file = hf_hub_download(
  File "/opt/conda/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 112, in _inner_fn
    validate_repo_id(arg_value)
  File "/opt/conda/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 160, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/home/code/data/lora_models/unsighing'. Use `repo_type` argument if needed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/lorax-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.9/site-packages/lorax_server/cli.py", line 81, in serve
    server.serve(
  File "/opt/conda/lib/python3.9/site-packages/lorax_server/server.py", line 262, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/conda/lib/python3.9/site-packages/grpc_interceptor/server.py", line 159, in invoke_intercept_method
    return await self.intercept(
> File "/opt/conda/lib/python3.9/site-packages/lorax_server/interceptor.py", line 21, in intercept
    return await response
  File "/opt/conda/lib/python3.9/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 82, in _unary_interceptor
    raise error
  File "/opt/conda/lib/python3.9/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 73, in _unary_interceptor
    return await behavior(request_or_iterator, context)
  File "/opt/conda/lib/python3.9/site-packages/lorax_server/server.py", line 153, in LoadAdapter
    self.model.load_adapter(adapter_id, adapter_source, adapter_index)
  File "/opt/conda/lib/python3.9/site-packages/lorax_server/models/flash_causal_lm.py", line 763, in load_adapter
    module_map, adapter_config = load_module_map(self.model_id, adapter_id, adapter_source, weight_names)
  File "/opt/conda/lib/python3.9/site-packages/lorax_server/utils/adapter.py", line 28, in load_module_map
    adapter_config = LoraConfig.from_pretrained(config_path)
  File "/opt/conda/lib/python3.9/site-packages/peft/utils/config.py", line 121, in from_pretrained
    raise ValueError(f"Can't find '{CONFIG_NAME}' at '{pretrained_model_name_or_path}'")
ValueError: Can't find 'adapter_config.json' at '/home/code/data/lora_models/unsighing'

2023-11-22T18:44:06.970137Z ERROR lorax_client: router/client/src/lib.rs:33: Server error: Can't find 'adapter_config.json' at '/home/code/data/lora_models/unsighing'
2023-11-22T18:44:06.970156Z  INFO lorax_router::loader: router/src/loader.rs:184: FAILED loading adapter /home/code/data/lora_models/unsighing/
2023-11-22T18:44:06.970176Z  INFO lorax_router::queue: router/src/queue.rs:125: set adapter /home/code/data/lora_models/unsighing/ status to Errored
2023-11-22T18:44:06.970219Z  INFO lorax_router::loader: router/src/loader.rs:240: terminating adapter /home/code/data/lora_models/unsighing/ loader
```

**Comment by tgaddair** [comment]
Hey @abhibst, going through the full error report again, I think the issue here is due to the differences in directory structure between your local machine and the docker container (I was assuming you were running these tests in the Docker container, but after looking over it again, it seems you're running them locally).

In your case, your adapter resides in a local directory called `/home/code/data/lora_models/unsighing`, so you should init the docker container with the following:

```
volume=/home/code/data
docker run --gpus '"device=3"' --shm-size 1g -e HUGGING_FACE_HUB_TOKEN=XXXXX -p 8082:82 -v $volume:/data ghcr.io/predibase/lorax:latest --model-id $model --quantize bitsandbytes
```

Setting `volume=/home/code/data` is the crucial step here (apologies if you already did this, but just wanted to be very explicit about environment setup).

Then when querying the adapter:

```
from lorax import Client
URL="http://127.0.0.0:8082"
client = Client(URL,timeout=20)

adapter_id="/data/lora_models/unsighing"
adapter_source="local"
client.generate(prompt,max_new_tokens=128,temperature=0.001,adapter_id=adapter_id,adapter_source=adapter_source).generated_text
```

Here the difference from what you provided is we use the root `/data` directory rather than the relative `./data` path.

Sorry for the confusion from before. Please give that a shot if you haven't already and let me know how it goes!

**Comment by abhibst** [comment]
@tgaddair , Thanks for all the help . Finally it works , with above suggestions , Amazing work done by LoraX team 🚀

**Comment by tgaddair** [comment]
Awesome! Thanks for confirming, and glad you got it working :)
